
-- o only adds indentation, and not a comment
vim.api.nvim_create_autocmd("FileType", {
  pattern = "*",
  callback = function()
    -- 'o' removes comment leader insertion on 'o'/'O'
    -- 'r' removes comment leader insertion on <Enter> in Insert mode
    vim.opt_local.formatoptions:remove({ "o" })
  end,
})

-- --- Filetype specific ---
-- autocmd keymap overrides have to be AFTER global overrides
-- .tex files visual jk
vim.api.nvim_create_autocmd("FileType", {
  pattern = { "tex", "markdown", "plaintex", },
  callback = function()
    vim.keymap.set('n', 'j', 'gj', { buffer = true })
    vim.keymap.set('n', 'k', 'gk', { buffer = true })
    vim.keymap.set('n', '<leader>ca', function()
      -- This triggers the code action specifically for ltex
      vim.lsp.buf.code_action({
        filter = function(a) return a.title:match("Add .* to dictionary") end,
        apply = true,
      })
    end, { desc = "LTeX: Add word to dictionary" })
  end,
})

-- Autocommand to make specific buffers closeable with 'q'
-- find out file type using `:set filetype?`

vim.api.nvim_create_autocmd("FileType", {
  pattern = { "fugitive", "lspinfo", "git", "help", "man", "gitsigns.diff", "gitgraph", "qf" },
  callback = function(args)
    vim.keymap.set('n', 'q', '<cmd>bwipeout!<CR>', { buffer = args.buf, silent = true })
  end,
})

-- fugitive diff view
-- vim.api.nvim_create_autocmd("BufWinEnter", {
--   desc = "Map 'q' to close Fugitive diff windows",
--   callback = function(args)
--     -- Check if this buffer was generated by Fugitive (e.g., "blob", "index")
--     local fugitive_type = vim.b[args.buf].fugitive_type
--
--     if fugitive_type then
--       vim.keymap.set("n", "q", "<cmd>diffoff | close<CR>", {
--         buffer = args.buf,
--         silent = true,
--         nowait = true,
--       })
--     end
--   end,
-- })

vim.api.nvim_create_autocmd("BufWinEnter", {
  desc = "Close diff panes cleanly with q",
  callback = function(args)
    local is_fugitive_buf = vim.b[args.buf].fugitive_type ~= nil
        or vim.api.nvim_buf_get_name(args.buf):find("^fugitive://") ~= nil

    -- If we are inside a Fugitive buffer OR a diff split
    if is_fugitive_buf or vim.wo.diff then
      vim.keymap.set("n", "q", function()
        if is_fugitive_buf then
          -- Close the fugitive preview window and turn off diff mode in remaining window
          vim.cmd("diffoff | close")
        else
          -- If pressed in the main local file during a diff, reset diffing
          vim.cmd("diffoff")
        end
      end, { buffer = args.buf, silent = true, nowait = true })
    end
  end,
})

-- vim.api.nvim_create_autocmd({ "BufReadCmd", "BufWinEnter" }, {
--   pattern = "fugitive://*",
--   desc = "Map 'q' to close fugitive protocol buffers",
--   callback = function(args)
--     vim.keymap.set("n", "q", "<cmd>diffoff | close<CR>", {
--       buffer = args.buf,
--       silent = true,
--       nowait = true,
--     })
--   end,
-- })

-- close q:, q/ and  q? with q
vim.api.nvim_create_autocmd("CmdwinEnter", {
  callback = function(args)
    vim.keymap.set('n', 'q', '<cmd>quit<CR>', { buffer = args.buf, silent = true })
  end,
})
-- # Yanking
vim.api.nvim_create_autocmd('TextYankPost', {
  desc = 'Highlight when yanking (copying) text',
  group = vim.api.nvim_create_augroup('kickstart-highlight-yank', { clear = true }),
  callback = function()
    vim.highlight.on_yank({
      -- higroup = 'Visual',
      timeout = 200,
    })
  end,
})


